### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by ITSM4Z** [DapperDino/Discord-Bot-Tutorial#3]
Commands = Client.UseCommandsNext(commandsConfig); is shownig an error 
(0029: cannot implicitly convert type 'DSharpPlus.CommandsNext.CommandsNextExtension' to 'DSharpPlus.CommandsNext.CommandsNextConfiguration')
can you please help me?

**Comment by TheBunnies** [comment]
Make sure that the Commands property has the right type.

**Comment by ITSM4Z** [comment]
> Make sure that the Commands property has the right type.

that's my code until now

`using DSharpPlus;
using DSharpPlus.CommandsNext;
using DSharpPlus.EventArgs;
using DSharpPlus.Interactivity;
using Newtonsoft.Json;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;


namespace Bucket_Helper_Bot
{
    public class Bot
    {
        public DiscordClient Client { get; private set; }

        public CommandsNextConfiguration Commands { get; private set; }

        public async Task RunAsync()
        {
            var config = new DiscordConfiguration
            {

            };

            Client = new DiscordClient(config);

            Client.Ready += onClientReady;

            var commandsConfig = new CommandsNextConfiguration
            {
                
            };

            Commands = Client.UseCommandsNext(commandsConfig);

            await Client.ConnectAsync();


        }
        private Task onClientReady(object sender, ReadyEventArgs br)
        {
            return null;
        }
    }
}
`

**Comment by TheBunnies** [comment]
Change the Commands property to CommandsNextExstension type. You should learn C# first before making a bot.

**Comment by ITSM4Z** [comment]
> Change the Commands property to CommandsNextExstension type. You should learn C# first before making a bot.

Sorry i am a begginer in C# Unity, i am not familiar with the C# without unity
